station = {data : {estaciones:[
  {id:1,
  nombre : "Centenario",
  ubicacion : "Parque centenario",
  modelo : "EPA-2000",
  inicioactividad : "13/01/1996",
  marca: "Datalogger",
  estado : "Activo"},
  {id : 2,
  nombre : "Córdoba",
  ubicacion : "Callao y Córdoba",
  modelo : "EPAC-3000",
  inicioactividad : "12/11/1998",
  marca: "Datalogger 2",
  estado : "Activo"}
  ],
sensores :[
  {id: 1,
  estacion_id:1,
  nombre:"Temperatura",
  unidad:"°C",
  descripcion:"Sensor de temperatura en Celsius"},
  {id:2,
  estacion_id:1,
  nombre:"CO2",
  unidad:"PPM",
  descripcion:"Sensor de dióxido de Carbono"}
  ],
mediciones :[
  {id:1,
  timestamp:"29/07/2016",
  valor:15,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:2,
  timestamp:"29/07/2016",
  valor:16,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:3,
  timestamp:"29/07/2016",
  valor:17,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:4,
  timestamp:"29/07/2016",
  valor:207,
  unidad:"ppm",
  descripcion:"",
  sensor_id:2},
  {id:5,
  timestamp:"29/07/2016",
  valor:15,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:6,
  timestamp:"29/07/2016",
  valor:157,
  unidad:"ppm",
  descripcion:"",
  sensor_id:2}]}};
  
  
busqueda= {data : { estacion_id : 1,
  sensores :[
  {id: 1,
  estacion_id:1,
  nombre:"Temperatura",
  unidad:"°C",
  descripcion:"Sensor de temperatura en Celsius"},
  {id:2,
  estacion_id:1,
  nombre:"CO2",
  unidad:"PPM",
  descripcion:"Sensor de dióxido de Carbono"}
  ],
mediciones :[
  {id:1,
  timestamp:"29/07/2016",
  valor:15,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:2,
  timestamp:"29/07/2016",
  valor:16,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:3,
  timestamp:"29/07/2016",
  valor:17,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:4,
  timestamp:"29/07/2016",
  valor:207,
  unidad:"ppm",
  descripcion:"",
  sensor_id:2},
  {id:5,
  timestamp:"29/07/2016",
  valor:15,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:6,
  timestamp:"29/07/2016",
  valor:157,
  unidad:"ppm",
  descripcion:"",
  sensor_id:2}]}};

busquedaSensor = {data : { estacion_id : 1,
sensor_id: 1,
mediciones :[
  {id:1,
  timestamp:"29/07/2016",
  valor:15,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:2,
  timestamp:"29/07/2016",
  valor:16,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:3,
  timestamp:"29/07/2016",
  valor:17,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:4,
  timestamp:"29/07/2016",
  valor:207,
  unidad:"ppm",
  descripcion:"",
  sensor_id:2},
  {id:5,
  timestamp:"29/07/2016",
  valor:15,
  unidad:"°C",
  descripcion:"",
  sensor_id:1},
  {id:6,
  timestamp:"29/07/2016",
  valor:157,
  unidad:"ppm",
  descripcion:"",
  sensor_id:2}]}};
